GlowTales/GlowTales-Server

- glowTales/.github/workflows/main.yml
- glowTales/.gitignore
- glowTales/appspec.yml
- glowTales/scripts/deploy.sh
cicd 설정
잘 작동하는지 테스트를 위해 main 브랜치로 머지할 예정입니다.
> [SETTING] cicd 설정

- src/main/java/com/example/glowtales/controller/MemberController.java
- src/main/java/com/example/glowtales/controller/QuizController.java
- src/main/java/com/example/glowtales/domain/Quiz.java
- src/main/java/com/example/glowtales/dto/response/member/LearningLanguageResponseDto.java
- src/main/java/com/example/glowtales/dto/response/quiz/EssayQuestionResponseDto.java
- src/main/java/com/example/glowtales/dto/response/quiz/MultipleChoiceResponseDto.java
- src/main/java/com/example/glowtales/dto/response/quiz/QuizResponseDto.java
- src/main/java/com/example/glowtales/dto/response/quiz/SentenceArrangementResponseDto.java
- src/main/java/com/example/glowtales/dto/response/quiz/TotalQuizResponseDto.java
- src/main/java/com/example/glowtales/dto/response/tale/HomeInfoResponseDto.java
- src/main/java/com/example/glowtales/repository/LearningLanguageRepository.java
- src/main/java/com/example/glowtales/repository/QuizRepository.java
- src/main/java/com/example/glowtales/service/MemberService.java
- src/main/java/com/example/glowtales/service/QuizService.java
#49 
#17 
동화의 퀴즈와 정답 조회 API 구현 
사용자 학습 언어와 수준 조회 API 구현
DB에 더미데이터 넣은 후 테스트 예정입니다!
> [FEAT] #11 동화의 퀴즈와 정답 조회 API 구현  #13 사용자 학습 언어와 수준 조회 API 구현

- src/main/java/com/example/glowtales/controller/TaleController.java
- src/main/java/com/example/glowtales/dto/response/tale/LanguageTaleDetailResponseDto.java
- src/main/java/com/example/glowtales/service/TaleService.java
#50 
#014 단일 동화 조회, #015 단일 동화 다국어로 조회 API 구현
> [FEAT] #014 단일 동화 조회, #015 단일 동화 다국어로 조회 API 구현

- src/main/java/com/example/glowtales/controller/LanguageController.java
- src/main/java/com/example/glowtales/dto/language/LanguageDto.java
- src/main/java/com/example/glowtales/service/LanguageService.java
close #15 
동화 공부 시 언어 선택 API 구현
|기능|스크린샷|
|:--:|:--:|
||![스크린샷 2024-08-23 오전 8 55 54](https://github.com/user-attachments/assets/c0d92897-f851-4cbb-87cb-6e3804b84ce2)|
> [FEAT] findAll language 구현

- src/main/java/com/example/glowtales/controller/QuizController.java
- src/main/java/com/example/glowtales/controller/TaleController.java
- src/main/java/com/example/glowtales/domain/LanguageTale.java
- src/main/java/com/example/glowtales/domain/Quiz.java
- src/main/java/com/example/glowtales/domain/Tale.java
- src/main/java/com/example/glowtales/domain/Word.java
- src/main/java/com/example/glowtales/dto/response/quiz/EssayQuestionResponseDto.java
- src/main/java/com/example/glowtales/dto/response/quiz/SentenceArrangementResponseDto.java
- src/main/java/com/example/glowtales/dto/response/tale/TaleResponseDto.java
- src/main/java/com/example/glowtales/service/QuizService.java
- src/main/java/com/example/glowtales/service/TaleService.java
#13 
#11 
- 최근 학습한 동화 반환값에 최초 정답 수 필드 추가
- 최근 학습한 동화 / 아직 학습하지 않은 동화 api에 koreanVersion 변수 추가 (홈/학습 하기 화면에는 한국어 버전 동화만 보임)
이번엔 ERD도 수정 완료!
> [FEAT] 반환값 필드 추가, 내부 로직 수정

- src/main/java/com/example/glowtales/controller/TaleController.java
- src/main/java/com/example/glowtales/domain/LanguageTale.java
- src/main/java/com/example/glowtales/dto/response/tale/LanguageTaleDto.java
- src/main/java/com/example/glowtales/service/LanguageTaleService.java
- src/main/java/com/example/glowtales/service/PromptService.java
language tale의 공부 여부를 update하는 로직을 구현하였습니다.
close #18 
|기능|스크린샷|
|:--:|:--:|
|update 요청 시|<img width="707" alt="스크린샷 2024-08-23 오후 5 17 13" src="https://github.com/user-attachments/assets/11671e29-2169-41a5-8043-957aed480a98">|
> [FEAT] updateIsLearned 구현

- src/main/java/com/example/glowtales/service/TaleService.java
사진 객체 검출 결과값 반환시 같은 종류의 객체가 여러개일 경우 같은 키워드가 여러개 반환됨.
-> 프론트의 중복제거 요청에 따라 중복 제거 진행
deepL을 통한 cat 번역처리가 진행되지 않고 있음
임시적으로 해당 키워드만 코드를 통해 고양이로 반환되게 처리해놓은 상태임.
> [FEAT] 키워드 중복 제거 & cat 임시 번역 처리

- src/main/java/com/example/glowtales/controller/TaleController.java
- src/main/java/com/example/glowtales/service/TaleService.java
객체 추출 (키워드 추출 api) 에러 처리
객체 추출 에러 시 500, 에러는 안났지만, 추출한 키워드가 없을 경우 400 bad request로 에러 코드 반환
|기능|스크린샷|
|:--:|:--:|
> [FEAT] 객체 추출 에러 처리

- src/main/java/com/example/glowtales/controller/TaleController.java
- src/main/java/com/example/glowtales/dto/response/tale/TaleForm.java
- src/main/java/com/example/glowtales/service/PromptService.java
- src/main/java/com/example/glowtales/service/TaleService.java
동화 생성 시 keywords 필수조건 제거
merge 과정에서 taleService에서 conflict 나서 확인 부탁드립니당 @eunsu02 
|기능|스크린샷|
|:--:|:--:|
|||
> [FIX] 동화 생성 시 request 형식 변경

- src/main/java/com/example/glowtales/domain/LanguageTale.java
- src/main/java/com/example/glowtales/dto/response/tale/LanguageTaleDto.java
- src/main/java/com/example/glowtales/service/LanguageTaleService.java
- src/main/java/com/example/glowtales/service/PromptService.java
최초 학습 하는 경우가 아닐 경우 count만 업데이트 하도록 하는 로직 추가했습니다
|기능|스크린샷|
|:--:|:--:|
|||
> 최초 학습하는 경우가 아닐 경우 로직 추가

- src/main/java/com/example/glowtales/service/PromptService.java
퀴즈 및 핵심 단어&문장 생성 시 학습수준을 제대로 반영하지 못하는 버그 수정하였습니다.
> [REFACTOR] 프롬프트 학습수준 반영하도록 수정

- src/main/java/com/example/glowtales/controller/MemberController.java
- src/main/java/com/example/glowtales/controller/QuizController.java
- src/main/java/com/example/glowtales/controller/TaleController.java
- src/main/java/com/example/glowtales/dto/response/quiz/QuizResponseDto.java
에러를 대비한 반환값 형식 수정
기존에 하영이가 만들어놓은 result로 반환하도록 수정했습니다
에러 코드 / 처리에 관해 이야기해보면 좋을것 같아요
|기능|스크린샷|
|:--:|:--:|
|||
> [FEAT] 에러를 대비한 반환값 형식 수정

- src/main/java/com/example/glowtales/dto/response/quiz/QuizResponseDto.java
> [FEAT] dto 반환값에 언어 id 추가

- src/main/java/com/example/glowtales/GlowTalesApplication.java
- src/main/java/com/example/glowtales/controller/TaleController.java
- src/main/java/com/example/glowtales/domain/Tale.java
- src/main/java/com/example/glowtales/dto/response/tale/LanguageTaleAndLanguageDto.java
- src/main/java/com/example/glowtales/dto/response/tale/PostTaleDto.java
- src/main/java/com/example/glowtales/service/TaleService.java
close #74 
|기능|스크린샷|
|:--:|:--:|
|동화 생성 성공 시|![스크린샷 2024-08-26 오전 2 39 24](https://github.com/user-attachments/assets/3d6a0207-e42b-4544-8884-cce400f4fc22)|
> 동화 생성 시 반환 형태 변경

- src/main/java/com/example/glowtales/dto/response/tale/PostTaleDto.java
- src/main/java/com/example/glowtales/service/TaleService.java
오타 수정
|기능|스크린샷|
|:--:|:--:|
|||
> [FIX] 필드명 createAt -> createdAt으로 수정

- src/main/java/com/example/glowtales/controller/TaleController.java
> [FEAT] validate 추가

- src/main/java/com/example/glowtales/controller/TaleController.java
- src/main/java/com/example/glowtales/dto/response/tale/CreatedRecentlyTaleDto.java
- src/main/java/com/example/glowtales/dto/response/tale/TaleDto.java
- src/main/java/com/example/glowtales/repository/TaleRepository.java
- src/main/java/com/example/glowtales/service/MemberService.java
- src/main/java/com/example/glowtales/service/TaleService.java
close #83 
|기능|스크린샷|
|:--:|:--:|
|조회 시 response|![스크린샷 2024-08-26 오전 5 27 55](https://github.com/user-attachments/assets/2dc10092-0a58-4bac-b588-447414bb6cb4)|
> 최근 생성한 동화 조회 API 구현

- src/main/java/com/example/glowtales/dto/response/quiz/KeyWordsAndSentencesResponseDto.java
- src/main/java/com/example/glowtales/dto/response/quiz/TotalQuizResponseDto.java
- src/main/java/com/example/glowtales/dto/response/tale/LanguageTaleDetailResponseDto.java
- src/main/java/com/example/glowtales/repository/LanguageTaleWordRepository.java
- src/main/java/com/example/glowtales/repository/SentenceRepository.java
- src/main/java/com/example/glowtales/service/QuizService.java
- src/main/java/com/example/glowtales/service/TaleService.java
close #87 
퀴즈 반환 값에 핵심 문장 / 단어 추가
동화 반환값에 created_at 추가
단어장 반환 시 tale의 created_at 순으로 정렬
> [FEAT] 퀴즈 반환 값에 핵심 문장 / 단어 추가

- src/main/java/com/example/glowtales/dto/response/quiz/KeyWordsAndSentencesResponseDto.java
- src/main/java/com/example/glowtales/service/QuizService.java
퀴즈 반환 시 핵심 문장 / 단어에 languageId 추가
> [FIX] 퀴즈 반환 시 핵심 문장 / 단어에 languageId 추가

- src/main/java/com/example/glowtales/dto/response/tale/LanguageTaleDetailResponseDto.java
- src/main/java/com/example/glowtales/dto/response/tale/TaleResponseDto.java
> [FIX] 퀴즈 반환 시 createdAt 포멧 형식 수정

- src/main/java/com/example/glowtales/domain/LanguageTale.java
- src/main/java/com/example/glowtales/dto/response/tale/TaleWithKoreanTitleResponseDto.java
fistQuizCount 삭제 후 firstQuizCount로 연결
> [FIX] 변수명 오타 수정, 잘못 생성된 필드 삭제

- src/main/java/com/example/glowtales/service/TaleService.java
> [FIX] 단어장 중복 단어 제거

- src/main/java/com/example/glowtales/repository/TaleRepository.java
- src/main/java/com/example/glowtales/service/TaleService.java
> [FIX] 동화 생성일자 내림차순 정렬

- src/main/java/com/example/glowtales/controller/TaleController.java
- src/main/java/com/example/glowtales/dto/response/tale/HomeInfoResponseDto.java
- src/main/java/com/example/glowtales/service/TaleService.java
> [FIX] 사용자 정보 조회 api 로직 수정

- src/main/java/com/example/glowtales/GlowTalesApplication.java
> [FIX] 서버 시간대 한국으로 변경
